# Generated by Django 2.2.16 on 2022-06-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220622_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='slug',
        ),
    ]
