# Generated by Django 2.2.16 on 2022-06-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='описание произведения'),
        ),
    ]
